- hosts: all
  become: yes
  user: ubuntu
  gather_facts: yes
  pre_tasks:
  - name: 'update_repo'
    raw: 'apt-get update'
  - name: 'install_python'
    raw: 'apt-get install -y python'
  roles:
  - { role: install-k8s, tags: ["install_k8s_role"] }

- hosts: k8s-master
  become: yes
  user: ubuntu
  roles:
  - { role: create-cluster, tags: ["create_cluster_role"] }

- hosts: k8s-workers
  become: yes
  user: ubuntu
  roles:
  - { role: join-workers, tags: ["join_workers_role"] }

- hosts: k8s-master
  become: yes
  user: ubuntu
  roles:
  - { role: install-helm, tags: ["install_helm3_role"] }

- hosts: k8s-master
  become: yes
  user: ubuntu
  roles:
  - { role: install-manit-tools, tags: ["install_manit_tools_role"] }